---

plugins:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude: []

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - fluent-plugin-druid-query.gemspec
    - test/**/*.rb

Metrics/ClassLength:
  Exclude:
    - lib/fluent/plugin/in_druid_query.rb
    - test/**/*.rb

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Exclude:
    - test/helper.rb

Naming/MethodParameterName:
  Exclude:
    - lib/fluent/plugin/in_druid_query.rb

Style/Documentation:
  Enabled: false
